Raathigesh/majestic

src/renderer/components/topbar/test-summary.tsx

Fix for Issue #26 - Typo - Execution Summary "Test Suits" heading should be "Test Suites"

Change 'Test Suits' to 'Test Suites'

---

src/main/menu.ts
src/renderer/stores/Workspace.ts

Project switching works now. 
Would be good if someone else can test it (until we have some automated tests).
Steps:
1. Open a project. (Either by the button on the open screen, or via the new toolbar menu.
2. Confirm this project is open. Now open another project via the toolbar menu.
3. Confirm it has switched to the new project.
The exit button is pretty easy to test. :)

feat(menu): Add File subsection with Open Project and Exit

---

src/renderer/components/topbar/run-panel/panel.tsx

Refactored the run tests text into the tooltip to match other buttons, and added tooltips for stop/play.
Looks like this now:

Add stop/play tooltips

---

ui/app.tsx
ui/hooks/use-keys.ts
ui/search/index.tsx

* Fixed missing `key` prop warning in `Search`
* Changed triple period to ellipsis in search input placeholder
* Search input is focused when opened
* Search input can be dismissed by pressing `Escape`
I'd like to add some more keyboard-related shortcuts, but this should serve as a decent starting point for deciding whether this kind of functionality is desired, and if so, how it should be approached.

Search dismiss

---

ui/sidebar/file-item.tsx

Fixes issue #73 where longer file names are breaking file item styling and overflowing onto adjacent file items.  Using VSCode convention of obscuring the overflow text with ellipsis (`...`)
> Majestic file item with ellipsis overflow
> Majestic sidebar with ellipsis overflow
> VSCode Example

Fixes Issue #73 File Item Names Overflowing Incorrectly

---

integration/projects/basic/test-only.spec.js
server/api/workspace/test-item.ts
server/services/ast/inspector.ts
ui/test-file/index.tsx
ui/test-file/query.gql
ui/test-file/test-item.tsx
ui/test-file/tranformer.ts

`test.only`, `it.only`, `describe.only`, `fit` and `fdescribe` were not showing up in the UI.
In this commit I:
* Refactored `ast/inspector.ts` to ensure they are not excluded
* Added a gold outline to highlight them in the UI

Handle test.only & describe.only

---

package.json
scripts/webpack.server.config.js
server/index.ts
server/typings.d.ts
yarn.lock

Switch from using `opn` to `open` as its deprecated. Added `open` to webpack externals.
Tested and now works on Ubuntu without error

Added 'open' to externals so it works on Ubuntu (Fixes #76)

---

server/services/config-resolver.ts
server/services/jest-manager/index.ts

When Majestic runs in a working directory which has spaces in it,
(e.g. `/Users/foo/sunday coding/bar`), it won't load.
In the browser console, the error says:
```
Uncaught TypeError: Cannot read property 'projectRoot' of undefined
at App (app.tsx:134)
```
Running locally, printing out `stderr` from [project.ts](https://github.com/Raathigesh/majestic/blob/master/server/services/project.ts#L30) gives me something along the lines of:
```
module.js:538
throw err;
^
Error: Cannot find module '/Users/foo/sunday'
at Function.Module._resolveFilename (module.js:536:15)
```
Similar to issue #88.
I figured out that this is due to the paths weren't being enclosed with quotes, which otherwise would be misinterpreted as multiple arguments ([reference](https://nodejs.org/api/child_process.html#child_pro …

fix: jest path should be enclosed with quotes

---

.npmrc
package.json

`async` function doesn't work with node 6, so now the application should throw the warning on installation.
https://node.green/#ES2017-features-async-functions

add minimum node engine ">=8.0" required in package.json

---

server/api/app/resolver.ts

Uses the Open In Editor button to open in the editor set by `$EDITOR` if `code` is not valid on your platform.

Open In Env EDITOR

---

ui/sidebar/index.tsx

This closes #115 (my bad, I referenced the wrong issue id previously).
I changed the code to such that it will only filter the failed test files when there are actually failed items in the list (because otherwise it would filter the files to empty). Also another small fix on the UI to highlight the failed test toggle button when activated.
This fixes the issue as far as the use case in #115 is concerned, but if it doesn't, let me know! Thanks for this awesome tool btw.

fix(sidebar): missing files after fixing failed tests

---

ui/app.tsx

This is just just a minor thing I noticed. When resizing the pane to the left, exceeding the first pane's minimum width, the second pane's width keeps increasing, eventually overflows the browser viewport. See the gif for details:
I think both of the panes need to fill up the viewport responsively (since there is no horizontal scrollbar as well). So, my idea is that the second pane should not exceed 100% - 300px in width, since the first pane has a minimum width of 300px.
Let me know what you think! Thank you.

fix(pane2): incorrect max width overflows the browser size

---

README.md
ui/hooks/use-keys.ts
ui/sidebar/index.tsx
ui/test-file/index.tsx

Addresses issue #150, also relevant to #124. 
This is a very minor change to prevent keyboard shortcuts from firing browser commands (such as save). If anyone who isn't using Chrome is reading, let me know if it looks like these new shortcuts will cause problems in other browsers, and I will change them.
It's worth noting that there seems to be a keyboard repeat issue with the watch shortcut. I t looks like the logic is triggering on every render when the keys are held down, requiring a very quick key press to keep it in watch mode. I can create a bug if you'd like.

Reassigned shortcut keys for browser compatibility.

---

ui/test-file/console-panel/index.tsx

Use `pre` tag to properly format HTML
🚨 Add `index` as key to `map` inside `console-panel/index.tsx`. This is to get rid of the error message in the console. Since we don't have any identifier for each log. React anyway defaults to using index as key when not explicitly given a key. 
Often times when working with tests I have to do `console.log(component.debug()` which outputs a prettified html code onto the console. Majestic however shows the whole component in a single line which can be hard to debug. 
Before: 
After:

✨ Pretty Printing HTML in console.logs.

---

.babelrc
package.json
yarn.lock

🚨 Add babel-plugin-styled-components to `.babelrc`
🚨 Update `yarn.lock`
Sorry if it was intentional to not have this plugin in `.babelrc`.
Feel free to close this PR if you think it doesn't add value!

🚛 Upgrade babel-plugin-styled-components to 1.10.6 from 1.8.0

---

package.json
server/services/ast/parser.ts

with a pointer from @raathigesh I was able to add support to babel which allows unit tests to contain statements that use the new optional chaining syntax.
This is necessary because Majestic processes the unit test file with a locally configured copy of babel. We had to add the experimental plugin for optional chaining to babel.
This fixes issue #164

support optional chaining in unit test files

---

integration/cypress/integration/basic/basic-functionality.js
integration/projects/basic/__snapshots__/test-snapshot-failure.spec.js.snap
integration/projects/basic/package-lock.json
integration/projects/basic/package.json
integration/projects/basic/test-snapshot-failure.spec.js
integration/projects/basic/test-snapshot-text.spec.js
ui/test-file/index.tsx
yarn.lock

Newer Jest versions had different failure text.
I also made a test that makes sure we don't show snapshot button by accident when the test itself contains the word 'snapshot'

Fix hidden update snapshots button

---

ui/test-file/summary/index.tsx

This fixes issue #159 where the summary used to push the action 
buttons off the edge of the screen as the screen got smaller. 
Now the action buttons wrap to the next line.

159 wrap summary

---

server/api/app/resolver.ts
ui/test-file/open-failure.gql
ui/test-file/test-item.tsx

This adds the feature requested in #184 .

Launch editor on error

---

ui/test-file/index.tsx
ui/test-file/summary/index.tsx

as outlined in #193, this change introduces an isUpdating flag and uses that flag to 
control the animated background of the file summary area. This makes it much easier
to determine if the test is currently running or if the results shown can be trusted.

193 better indication test run status

---

server/services/project.ts

This addresses issue #199. 
by normalizing the root path, the user is free to specify the root path in either windows or unix format and majestic will silently convert it to the format that is appropriate for the platform being used.

normalize root path

---

ui/sidebar/index.tsx

Add collapse all and expand all to the tree control
I have added two icons to the tree control icon area. The first collapses
all the directories in the tree except the root directory and the other
expands all the directories in the tree.
This makes it much easier to find a test file to work on.
I also put the icons on the right side because that is where the
"show failing tests only" icon appears and it seemed that they were
similar types of operations. Then I realized that the collapse / expand
don't make sense when the show failing test only icon is toggled
so in that case I hide the icons.
And then because the icons vanish and appear, I rearranged their
position to what I thought made more sense.
Refresh: is always present and always in a fixed location on the right
The most important …

collapse all tree control (#203)

---

server/api/workspace/resolver.ts
server/api/workspace/test-result/file-result.ts
server/services/results.ts
ui/test-file/index.tsx

This addresses issue #201
When a user starts a test run, the old results are still shown, but they are dimmed (50% opacity) while the test is running. When the new test results are available, the new test results replace the old test results.
The difference between this and the old behaviour was that in the old behaviour, the old test results were discarded as soon as the test run started. This causes the user to have to sit there waiting for the test to complete before seeing the information that used to be there before the test started if there were additional test failures that were fixed with the new test run. It led to a waste of developer time.
Note, this is the second attempt to bring these changes over. The first PR attempt was done from a corrupt branch in my fork because of a …

203 keep last result

---

server/api/app/resolver.ts
ui/test-file/index.tsx
ui/test-file/summary/index.tsx
ui/test-file/summary/open-snap-in-editor.gql

This PR does two things. It implements #186 and #191. 
For  #186, this creates a new button to load the snapshot in the editor so that you can quickly
see the snapshot - useful when writing tests. 
I had created FR #191 because I wanted a way to generate the snapshots, not realizing that the
button was already there. This change makes the button visible all the time. The reason for that
is that there are times when you know the snapshots are out of date and need to be updated.
If you run the tests just to have them fail, it wastes time. Having this button visible all the time
saves time because you can generate the snapshots when you know they are out of date.

186 open snapshot in editor

---

server/services/ast/inspector.ts

Fixes #212.
Empty templates would cause a crash as well as templates with only one variable.

fix: fixes crash when test name is an empty template

---

server/services/cli.ts
ui/test-file/console-panel/index.tsx

👋 
I have been using this tool at work and it's been a life safer, the only issue I have is that when you try to log some HTML because of the ANSI color codes the HTML will show up like this:
This PR does a small cleanup in the result and strips all of this and the HTML will show up clean

escape ansi color codes in string console.logs
